# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml

import:
  # uncomment the flavour you want below:
#  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
  - ~/.config/alacritty/rosepine/rose-pine-moon.yml


# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: xterm-256color

# Font configuration
font:
  normal:
    family: "IosevkaTerm Nerd Font"
    style: "Bold"


  # Point size
  size: 12.0

cursor:
  # Cursor style
  style:

    shape: Block

    blinking: On

  vi_mode_style: Block

window:
  opacity: 0.9
