cookie: "OptanonAlertBoxClosed=2023-06-02T19:31:23.152Z; sp_dc=AQAnn9LlBgZvejU4RcOKBLlsRucci0xgQ0xISpXhhtAiTINIZKMdrfZ11gbvzgmVWUb7zg2R9QGfnN9BmcOiMHjCFfjVn0MTIMCqfXnbFKl3KdXdPQKj60XT4bvqFm0qE_N0snwaJtskZtzlIKSqKMwJK7jDMjI; sp_key=ca79045d-a7c0-4433-900f-6fc1727638e9; sp_m=fr; sp_t=f7f37a01-5c09-4aca-a493-23565dfc8c83; sp_new=1; sp_landing=https%3A%2F%2Fwww.spotify.com%2Ffr%2Faccount%2Foverview%2F%3Futm_source%3Dspotify%26utm_medium%3Dmenu%26utm_campaign%3Dyour_account; sp_landingref=https%3A%2F%2Faccounts.spotify.com%2F; sp_last_utm=%7B%22utm_campaign%22%3A%22your_account%22%2C%22utm_medium%22%3A%22menu%22%2C%22utm_source%22%3A%22spotify%22%7D; sp_gaid=0088fc73b9b7e2feeb75d49f78cf878aed4c8e3f44f61e29127286; eupubconsent-v2=CPsxqJfPsxqJfAcABBENDNCgAP_AAAAAAAYgGWNBjS-vRwvr-_76brswcY0G0dB9Y-EyhgfFBKABHboUMJ0FwGA5oFVCkKgKCAYgMUJBIEEgCDEUCVEgaoEFDiGAIEiUBLEIICNAEDAAAQBAAAlQFA6gAAAAgbgMCQAAgBKAAFIAAEAAABwQBeAAIABYADwALgAfABkADwAHwAQwAjABJACqAFgALYAYgA5gB6AEIAIYARYAjgBLACaAGGAMgAcQA5wB1QD2APgAfoBAwCDgEXAJMAUsAq8BhAGKANwAegBF4CPQEiAJWAUOApsBbADFgkAoACoAGQAQAA0ACIAEwAJ4ApQB3gLzDAGAAFgAXACEAEYAJIATwAqABbADEAIYAUgAyABqgDiAHOASYAloBSwDZAHUAReAkQBQ4DFhABQABYAFwAhABGACSAE8ALYAYgBDACkAGQAOIAc4BJgCWgFLAReAkQBQ4DFhQAmAIQAhgBiAEcAKQAaoA4gCWgI9ASCMADwBCAEMAMQAjgBSADiAJaAj0cBBAAEAAsAB4AFwAPwAxADIAHIAPIAfACCAEMAIwAVQAsABbAC6AF8AMQAZgA5gB6AEIAIYARwAlgBMACagFGAUgAsQBZgDCAGQANUAcQA5wB1ADuAHsAP0AgcBBwEIgIsAi4BJgCbAE4AKXAVcBWQDAwGEAYoA3AB1ADyAHoARAAioBF4CPQEggJEASsAocBTACmwFlALYAYsOgFgAVAAyACAAGgARAAmABPAFKAO8BeYDLCABcABYAMQAggBDACqAF8AMQAegBHACkAFiANUAcQA5wCcAFLgKuArMBhAGKAOoAdsA9ACPQEgkIAYAGQAmADvJAGwABAALAAuADEAHIAPIAqACqAF8AMQAbQBCACGAEcAKQAdwBBwCWwFXAVkAxQB1AEVAIvASIAlYBZQC2AGLEoAoAGQAiABMAHeAvMoAxAAEAAsAC4AH4AYgBkADkAHgAPwAhgBGgCoAKoAWAAvgBiADMAG0AOYAhABDACOgFGAUgAsQBhADiAHOAOoAdwA_QCDgEWAJaATYApcBVwFZALrAYQBigDXgG4AO2AeQA9ACLwEegJEAUOApgBTYC2AGLFIBQAFQAMgAgABoAEQAJgATwBSgDvAXmAAA.f_gAAAAAAAAA; OptanonConsent=isIABGlobal=false&datestamp=Thu+Jul+13+2023+20%3A42%3A39+GMT%2B0200+(Central+European+Summer+Time)&version=6.26.0&hosts=&consentId=7f0bfb63-4d9a-4986-977b-8ff80751c347&interactionCount=1&landingPath=NotLandingPage&groups=s00%3A1%2Cf00%3A1%2Cm00%3A1%2Ct00%3A1%2Cf11%3A1%2Ci00%3A1%2CSTACK3%3A1%2CSTACK11%3A1%2CSTACK20%3A1&AwaitingReconsent=false&geolocation=FR%3BIDF"
player: spotify
host: lyricsapi.vercel.app
ignoreErrors: true
timerInterval: 200
updateInterval: 2000
style:
  hAlignment: top
  before:
    background: ""
    foreground: "#a6da95"
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: true
  current:
    background: ""
    foreground: "#a6da95"
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: "#cad3f5"
    bold: false
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: true
pipe:
  length: 0
  overflow: word
mpd:
  address: 127.0.0.1:6600
  password: ""
mopidy:
  address: 127.0.0.1:6680
mpris:
  players: []
